apiVersion: apps/v1
kind: Deployment
metadata:
 name: clayson-frederickson
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: clayson-frederickson
  template:
    metadata:
      labels: 
        app: clayson-frederickson
    spec:
      containers:
      - name: clayson-frederickson
        image: gcr.io/team-1-group-project/team-1-website
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: claysonpod-service
spec:
  selector:
    app: clayson-frederickson
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
