apiVersion: apps/v1
kind: Deployment
metadata:
  name: ernest-danso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ernest-danso
  template:
    metadata:
      labels:
        app: ernest-danso
    spec:
      containers:
      - name: ernest-danso
        image: gcr.io/team-1-group-project/team-1-website:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
