apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikey-stong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikey-stong
  template:
    metadata:
      labels:
        app: mikey-stong
    spec:
      containers:
      - name: mikey-stong
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
