apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikey-stong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikey-stong
  template:
    metadata:
      labels:
        app: mikey-stong
    spec:
      containers:
      - name: mikey-stong
        image: gcr.io/team-1-group-project/team-1-website
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M

---
apiVersion: v1
kind: Service
metadata:
  name: mikeys-pod-service
spec:
  selector:
    app: mikey-stong
type: LoadBalancer
ports:
- port: 80
  targetPort: 3000