apiVersion: apps/v1
kind: Deployment
metadata:
 name: spencer-baker
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: spencer-baker
  template:
    metadata:
      labels: 
        app: spencer-baker
    spec:
      containers:
      - name: spencer-baker
        image: gcr.io/team-1-group-project/team-1-website:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M